swagger: "2.0"
info:
  description: "API Application"
  version: 1.0.0
  title: Swagger API Application
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: localhost:8080
basePath: /api/v1
tags:
  - name: Location
    description:  Operations about Location
  - name: Employee
    description: Operations about Employee
securityDefinitions:
  jwt:
    description: OpenStack Keystone Authentication
    type: apiKey
    in: header
    name: authorization
schemes:
  - http
paths:
  /location:
    post:
      tags:
        - Location
      summary: Add a new location belongs store
      security: 
        - jwt: []
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Location object that needs to be added to the store
          required: false
          schema:
            $ref: "#/definitions/LocationModel"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        "400":
          description: Client Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      tags:
        - Location
      summary: Update location of store
      security: 
        - jwt: []
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Location object that needs to be update 
          required: true
          schema:
            $ref: "#/definitions/LocationModel"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        "400":
          description: Client Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      tags:
        - Location
      summary: Get location of store
      security: 
        - jwt: []
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: _id
          description: Id location 
          required: false
          type: string
        - in: query
          name: status
          description: status location [ACTIVE, INACTIVE] 
          required: false
          type: string
          enum: 
            - ACTIVE
            - INACTIVE
        - in: query
          name: name
          description: name location 
          required: false
          type: string
        - in: query
          name: owner
          description: owner location 
          required: false
          type: string
        - in: query
          name: sortBy
          description: field need to sort 
          required: false
          type: string
          enum:
            - status
            - name
            - created_at
          default: created_at
        - in: query
          name: orderBy
          description: type sort 
          required: false
          type: string
          enum:
            - DESC
            - ASC
          default: DESC
        - in: query
          name: pageNum
          description: page number 
          required: false
          type: integer
          default: 0
        - in: query
          name: pageSize
          description: page size 
          required: false
          type: integer
          default: 100
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        "400":
          description: Client Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      tags:
        - Location
      summary: delete location of store
      security: 
        - jwt: []
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: _id
          description: Id of location needs to delete
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        "400":
          description: Client Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /location/status/{_id}:
    put:
      tags:
        - Location
      summary: Update location status
      security: 
        - jwt: []
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: _id
          description: Id of location needs to be update
          required: true
          type: string
        - in: body
          name: body
          description: Location object that needs to be update 
          required: true
          schema:
            properties: 
              status:
                type: string
                enum:
                  - ACTIVE
                  - INACTIVE
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        "400":
          description: Client Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /location/{_id}:
    get:
      tags:
        - Location
      summary: Get location by id
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: _id
          description: Id of location needs to be update
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        "400":
          description: Client Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /employee:
    post:
      tags:
        - Employee
      summary: Add a new employee
      security: 
        - jwt: []
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: employee object that needs to be added
          required: true
          schema:
            $ref:  "#/definitions/EmployeeModel"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        "400":
          description: Client Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      tags:
        - Employee
      summary: update a employee
      security: 
        - jwt: []
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: employee object that needs to be updated
          required: true
          schema:
            $ref:  "#/definitions/EmployeeModel"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        "400":
          description: Client Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      tags:
        - Employee
      summary: delete array list employee
      security: 
        - jwt: []
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: arrId
          type: array
          items:
            type: string
          description: array id (maximum 20)
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        "400":
          description: Client Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      tags:
        - Employee
      summary: get employee
      security: 
        - jwt: []
      description: ""
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: _id
          type: string
          description: id
          required: false
        - in: query
          name: fullname
          type: string
          description: fullname
          required: false
        - in: query
          name: gen
          type: string
          description: gen
          required: false
        - in: username
          name: username
          type: string
          description: username
          required: false
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        "400":
          description: Client Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        "500":
          description: Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  SuccessResponse:
    properties:
      code:
       type: number
      message:
        type: string
      value:
        type: array
        items:
          type: object
  ErrorResponse:
    properties:
      code: 
        type: number
      message: 
        type: string
      error:
        type: object 
  EmployeeModel:
    properties: 
      _id:
        type: string
        example: 5b2b1b7db7945e2ff4d68116
      fullname: 
        type: string
        example: Trần Đức Ninh
      gen: 
        type: string
        example: 163313968
      email:
        type: string
        example: tranducninhnd94@hotmail.com
      address: 
        properties:
          ward: 
            type: string
          district: 
            type: string
          province: 
            type: string
      username:
        type: string
        example: tranducninh
      password: 
        type: string
        example: abc13579
      facebookPage: 
        type: array
        items:
          properties:
            url: 
              type: string 
        example:
          - url: https://facebook.com.vn/tranducninhnd94
          - url: https://facebook.com.vn/tranducninhnd95
      phoneNumber:
        type: array
        items: 
          properties:
            number:
              type: string
        example: 
          - number: 0166-97-09094
          - number: 0166-97-09095
      avatar: 
        type: string
        example: http://localhost:8080/images/avater/default.jpg
      work_places: 
        type: array
        items:
          properties:
            location: 
              type: string
            roles:
              type: array
              items:
                properties:
                  name:
                    type: string
                  permission:
                    type: array
                    items:
                      type: string
            salary:
              properties:
                baseSalary: 
                  type: number
                positionSalary:
                  type: number
                allowanceSalary:
                  type: number
            monthlySalary:
              type: array
              items:
                properties:
                  status: 
                    type: string
                    enum: 
                      - RECEIVED
                      - NOT_RECEIVED
                  dateReceived:
                    type: string
                    format: date-time
                  baseSalary: 
                    type: number
                  positionSalary:
                    type: number
                  allowanceSalary:
                    type: number
                  promotionSalary:
                    type: number
            dateWorking: 
              type: string
              format: date
        example:
          - location:
              _id: 5b2b1b7db7945e2ff4d68116
              name: Location 1
            roles:
              - name: Employee
                permission:
                  - permission 1
                  - permission 2
            salary:
              baseSalary: 2000000
              positionSalary: 0
              allowanceSalary: 0
            monthlySalary:
              - status: NOT_RECEIVED
                dateReceived: 2018-06-28T06:29:06.984Z
                baseSalary: 2000000
                positionSalary: 0
                allowanceSalary: 0
                promotionSalary: 0
              - status: RECEIVED
                dateReceived: 2018-05-28T06:29:06.984Z
                baseSalary: 2000000
                positionSalary: 0
                allowanceSalary: 0
                promotionSalary: 0
            dateWorking: 2017-07-21 
      latestAcess: 
        type: string
        format: date-time
      createdAt: 
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
  LocationModel:
    properties: 
      _id:
        type: string
        example: 5b2b1b7db7945e2ff4d68116
      name: 
        type: string
        example: location 1
      address: 
        properties:
          ward: 
            type: string
          district: 
            type: string
          province: 
            type: string
        example:
          ward: ward
          district: district
          province: province
      phoneNumber:
        type: array
        items: 
          type: string
        example: 
          - 163313968
      status:
        type: string
        enum:
          - INACTIVE
          - ACTIVE
        default: ACTIVE    
      fax:
        type: string
      owner:
        type: string
        example: Trần Đức Ninh
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time

